#!/usr/bin/env bash
# Print SyncBot GCP Terraform outputs for GitHub variables (WIF, deploy).
# Run from repo root:  infra/gcp/scripts/print-bootstrap-outputs.sh
# Requires: terraform in PATH; run from repo root so infra/gcp is available.
#
# Flow: terraform output (full) -> suggested variable names for CI.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GCP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ ! -d "$GCP_DIR" ]] || [[ ! -f "$GCP_DIR/main.tf" ]]; then
  echo "Error: infra/gcp not found (expected at $GCP_DIR). Run from repo root." >&2
  exit 1
fi

echo "=== Terraform Outputs (Infra/GCP) ==="
echo ""

cd "$GCP_DIR"
if ! terraform output -json >/dev/null 2>&1; then
  echo "Error: Terraform state not initialized or no outputs. Run 'terraform init' and 'terraform apply' in infra/gcp first." >&2
  exit 1
fi

terraform output

echo ""
echo "=== Suggested GitHub Actions Variables ==="
echo "GCP_PROJECT_ID      = $(terraform output -raw project_id 2>/dev/null || echo '<set from output project_id>')"
echo "GCP_REGION          = $(terraform output -raw region 2>/dev/null || echo '<set from output region>')"
echo "GCP_SERVICE_ACCOUNT = $(terraform output -raw deploy_service_account_email 2>/dev/null || echo '<set from output deploy_service_account_email>')"
echo "Artifact Registry   = $(terraform output -raw artifact_registry_repository 2>/dev/null || echo '<set from output artifact_registry_repository>')"
echo "Service URL         = $(terraform output -raw service_url 2>/dev/null || echo '<set from output service_url>')"
echo ""
echo "For deploy-gcp.yml also set: GCP_WORKLOAD_IDENTITY_PROVIDER (after configuring WIF for GitHub)."
echo ""
echo "TOKEN_ENCRYPTION_KEY is generated by this Terraform apply and stored in Secret Manager."
echo "Back it up after apply (see docs/DEPLOYMENT.md). Secret: $(terraform output -raw token_encryption_secret_name 2>/dev/null || echo '<token_encryption_secret_name>')"
